export const Carddet = [
  {
    Image: "/a (1).jpg",
    name: "Ethan Fender",
    likes: "347",
    views: "2.8k",
  },
  {
    Image: "/a (2).jpg",
    name: "lmao Fender",
    likes: "800",
    views: "489",
  },
  {
    Image: "/a (3).jpg",
    name: "Alex Krugli",
    likes: "44k",
    views: "10k",
  },
  {
    Image: "/a (4).jpg",
    name: "Ramy Wafaa",
    likes: "890",
    views: "20k",
  },
  {
    Image: "/a (5).jpg",
    name: "Marcato Studio",
    likes: "7.8k",
    views: "755",
  },
  {
    Image: "/a (6).jpg",
    name: "lmao Fender",
    likes: "560",
    views: "962",
  },
  {
    Image: "/a (7).jpg",
    name: "lmao Fender",
    likes: "894",
    views: "1.5k",
  },
  {
    Image: "/a (17).jpg",
    name: "lmao Fender",
    likes: "78k",
    views: "500",
  },
  {
    Image: "/a (9).jpg",
    name: "lmao Fender",
    likes: "452",
    views: "708",
  },
  {
    Image: "/a (10).jpg",
    name: "Julia Hanke",
    likes: "1.2k",
    views: "999",
  },
  {
    Image: "/a (11).jpg",
    name: "Marcato Studio",
    likes: "78",
    views: "8.9k",
  },
  {
    Image: "/a (12).jpg",
    name: "lmao Fender",
    likes: "5k",
    views: "305",
  },
  {
    Image: "/a (13).jpg",
    name: "lmao Fender",
    likes: "200",
    views: "620k",
  },
  {
    Image: "/a (14).jpg",
    name: "lmao Fender",
    likes: "851",
    views: "108",
  },
  {
    Image: "/a (15).jpg",
    name: "Julia Hanke",
    likes: "2.5k",
    views: "657",
  },
  {
    Image: "/a (16).jpg",
    name: "Marcato Studio",
    likes: "347",
    views: "2.8k",
  },
];
